Bring Your Own Resources
everware/everware pull request #205
Opened 2017-06-20 00:21 UTC by StrausMG

The branch adds a brand-new feature which allows to use custom servers for running containers.

2017-06-21 09:31 UTC, anaderi requested changes
please review

2017-06-21 09:31 UTC, anaderi commented on etc/byor_config.py
> +c.DockerSpawner.hub_ip_connect = c.JupyterHub.hub_ip
let's remove the last 2 lines. check that it doesn't break anything. if so, you can just load_subconfig('etc/local_config.py')

2017-06-21 09:31 UTC, anaderi commented on everware/_spawner_options_form.py
> +    (Click <a href="https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option"
should read:
Enter IP address and port of the Docker daemon running on your server.

2017-06-21 09:31 UTC, anaderi commented on everware/_spawner_options_form.py
> +<div style="margin-bottom: 0px;">
make separate html file in share/static/html and read it instead.

2017-06-21 09:31 UTC, anaderi commented on everware/spawner.py
move to ByorDockerSpawner class

2017-06-21 09:31 UTC, anaderi commented on etc/byor_config.py
> +c.DockerSpawner.hub_ip_connect = c.JupyterHub.hub_ip
just specify ByorDockerSpawner as spawner

2017-06-21 09:31 UTC, anaderi commented on everware/spawner.py
remove trailing space

2017-06-27 16:52 UTC, anaderi requested changes
and bump version as well

2017-06-27 16:52 UTC, anaderi commented on etc/byor_config.py
> +    c.ByorDockerSpawner.options_form = form.read()
move to ByorDockerSpawner.__init__

2017-06-30 12:50 UTC, merged

2017-07-04 19:41 UTC, yuvipanda commented
This is awesome! Thank you for working on this!

However, I have some concerns about security & authentication. If you open up a docker daemon without any authentication to the internet, that pretty much provides attackers with root on that machine with no effort. There already is malware that looks for these kinds of vulnerabilities - https://duo.com/blog/over-18000-redis-instances-targeted-by-fake-ransomware for one that attacked redis, http://www.securityweek.com/elasticsearch-servers-latest-target-ransom-attacks for elasticsearch, https://nakedsecurity.sophos.com/2017/01/11/thousands-of-mongodb-databases-compromised-and-held-to-ransom/ for mongodb, etc. Since docker allows much more arbitrary compute execution than the others did (except for elasticsearch - there were attacks that used ES to spawn a VM!), it is also potentially used as command & control center for malware / ransomware attacks (unpatched wordpress instances were used in cyberattacks related to the US '16 Election, for example https://www.wordfence.com/blog/2017/02/russia-election-hack-worpress-used/). 

Docker has TLS support for doing client authentication (https://docs.docker.com/engine/security/https/). This will require users to provide everware a certificate as well as the docker daemon URL - the client certificate can then be kinda used like a password (@betatim's idea!). This would be a huge improvement over plain unauthenticated docker endpoints. I hope you would consider implementing it, and more importantly *requiring* it - since otherwise people would just probably skip it.

Thanks!

2017-07-07 20:00 UTC, anaderi commented
Thanks Yuvi. It was just the first step. Tls part is on its way. Stay tuned!

2017-07-07 20:00 UTC, yuvipanda commented
tyvm! This is great :D